# Generated by Django 4.1.7 on 2023-03-25 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('category', models.CharField(choices=[('Laptop', 'laptop'), ('Headphones', 'Headphones'), ('Mouses', 'Mouses'), ('Keyboards', 'Keyboards'), ('Other', 'Other')], max_length=500, verbose_name='Category')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='Description')),
                ('image', models.CharField(default='https://tastystore.ru/design/no-photo.png?design=THEMENAME', max_length=10000, null=True, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(max_length=1000, verbose_name='Review Text')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Rating')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
            ],
        ),
    ]
